pdxshelter/config/routes.rb
Rails.application.routes.draw do

  mount Dashing::Engine, at: Dashing.config.engine_path
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :guests
  root to: 'guests#index'

end

pdxshelter/app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :user

  has_attached_file :tb_card, :styles => { :medium => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :tb_card, :content_type => /\Aimage\/.*\Z/

end

pdxshelter/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email

  has_many :guests

end

pdxshelter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #devise
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :username) }
  end
  #end devise

end

pdxshelter/app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @guests = Guest.all
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      flash[:notice] = "Guest created."
      redirect_to guests_path
    else
      render 'new'
    end
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])
    if @guest.update(guest_params)
      flash[:notice] = "Guest information updated"
      redirect_to guest_path(@guest)
    else
      render 'edit'
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    flash[:notice] = "Guest deleted from system"
    redirect_to guests_path
  end

private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :tb_card)
  end
end

pdxshelter/app/helpers/application_helper.rb
module ApplicationHelper
end

pdxshelter/app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  Shelter Dashboard
<% end %>

<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="PDXShelter" data-moreinfo=""></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="synergy" data-view="Meter" data-title="Capacity" data-min="0" data-max="100"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Guests" data-moreinfo="">
      </div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Costs" data-moreinfo="In quadrillions" data-prefix="$"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="convergence" data-view="Graph" data-title="Convergence" style="background-color:#ff9618"></div>
    </li>
  </ul>
</div>

pdxshelter/app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :tb_card %>
    <%= f.file_field :tb_card %>
  </div>
  <%= f.submit(class: "btn btn-primary") %>
<% end %>

pdxshelter/app/views/guests/edit.html.erb
<%= content_for(:title, "Edit guest | PDXShelter") %>

<h1>Edit Guest</h1>

<%= render 'form' %>

pdxshelter/app/views/guests/index.html.erb
<%= content_for(:title, "Guests") %>

<h1> Guests </h1>

<ul>
  <% @guests.each do |guest| %>
    <li><a href="/guests/<%= guest.id %>"> <%= guest.last_name %></a></li>
  <% end %>
</ul>

<%= link_to "Register New Guest", new_guest_path, class: "btn btn-default" %>

pdxshelter/app/views/guests/new.html.erb
<%= content_for(:title, "New Guest | PDXShelter") %>

<h1> New Guest </h1>

<%= render 'form' %>

pdxshelter/app/views/guests/show.html.erb
<%= content_for(:title, "#{@guest.first_name} #{@guest.last_name} | PDXShelters") %>

<h1><%= @guest.first_name%> <%= @guest.last_name %></h1>

<% if !@guest.tb_card.blank? %>
  <%= image_tag @guest.tb_card.url(:medium) %>
<% end%>

<p><%= link_to "Edit", edit_guest_path(@guest), class: "btn btn-default" %></p>

<p><%= link_to "Delete", guest_path(@guest),
                         confirm: "Are you sure?",
                         method: "delete",
                         class: "btn btn-danger"
%></p>

<p><%= link_to "Return to the guest listing", guests_path %></p>

pdxshelter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdxshelter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.username %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>

<!-- <%= yield %> -->

</body>
</html>

pdxshelter/app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= yield :title %></title>

    <%= javascript_include_tag 'dashing/application' %>
    <%= stylesheet_link_tag 'dashing/application' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="/favicon.ico">
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
      <div id="saving-instructions">
        <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
        <textarea id="gridster-code"></textarea>
      </div>
      <a href="#saving-instructions" id="save-gridster">Save this layout</a>
    <% end %>
  </body>
</html>